"$schema" = 'https://starship.rs/config-schema.json'

# asdf経由のコマンドが遅いためタイムアウトを増やす
command_timeout = 1000

[git_branch]
symbol = ''
format = '\([$symbol$branch(:$remote_branch)]($style)\) '

[package]
disabled = true

[gcloud]
disabled = true

[docker_context]
disabled = true
